version: "3"

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: iujoapp
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - "8080:80"
    restart: always
  app:
    container_name: nextjs
    image: docker-nextjs-dev
    depends_on:
      - mysql-db
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages
      - ./components:/app/components
      - ./public:/app/public
      - ./styles:/app/styles
      - ./services:/app/services
      - ./hooks:/app/hooks
      - ./utils:/app/utils
      - ./:/app/
