version: "3"

services:
  mysql-db:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: iujoapp
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - my_db:/var/lib/mysql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - "8080:80"
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000

volumes:
  my_db:
